title: The Work of Sepehr
subtitle: Sepehr's Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my digital portfolio. In this website, you will find a collection of my best work, showcasing my Software Engineering skills. I hope you enjoy browsing through my projects.

url: https://sepehrkianian09.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    # - text: Blog
    #   url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Sepehr Kianiangolafshani
author_bio: I am a Software Engineering Master's students at Aalto University. You can find about my experience in here.
author_email: "sepehr.kianian.r@gmail.com"
author_location: Finland
author_website_url: "https://sepehrkianian09.github.io/"
typewrite-text: Welcome to my Page!
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
show_author_work_experiences: true
author_work_experiences:
            - company_name: ISE Lab
              company_logo: ise-lab.png
              company_url: http://ise.ce.sharif.ir/
              designation: Research Assistant
              description: ⋄ We researched ways of improving state-of-the-art automatic code documentation approaches via augmentation methods. the target approaches were RAG and Code2Seq, and we were improving them by augmenting code metrics. We developed all the code bases for our experiment, and I was mainly involved during the whole research. ⋄ We developed the Code2Seq approach using Pytorch, and we used so many open-source LLMs, e.g. Lamma and Code-gemma, for RAG.
              visibility: true
            - company_name: GymTime
              company_logo: gymtime.jpg
              company_url: N/A
              designation: Co-Founder
              description: ⋄ GymTime startup was a gym reservation platform I had founded with my college colleagues, and besides software development, we did strategic planning, pivoting, and marketing activities together.
              visibility: true
            - company_name: Oxydev
              company_logo: oxydev.jfif
              company_url: N/A
              designation: Software Engineer
              description: ⋄ I was involved in the startup of Histopia, an MMORPG game on the web platform. One of our rivals was the Sandbox game. I had not developed a game before and I did not know anything about computer graphics. However, I did not give up the chance because I had a passion of it. Therefore, I told them I try to develop some prototype to see if I can make it. The result was good, and I learned a lot about so many aspects of game development during the project. I used so many capabilities of web development I did not know existed. And although we lost to our rivals, it was worth it for me.
              visibility: true

# Education
show_author_education_details: true
author_education_details:
              - college_logo: aalto_university_logo.jfif
                college_name: Aalto University
                college_url: https://www.aalto.fi/en
                college_degree: Software and Service Engineering
                description: Master of Science
                visibility: true
              - college_logo: sharif_university_of_technology_logo.jfif
                college_name: Sharif University of Technology
                college_url: https://en.sharif.ir/
                college_degree: Computer Engineering
                description: Bachelor of Science
                visibility: true

# Projects
show_author_project_details: false
author_project_details:
              # - project_thumbnail: gamershub.png
              #   project_title: Gamers Hub
              #   project_description: A Platform built for Gamers and Game Devs
              #   project_url: https://gamershub.in
              #   visibility: true

# social links
github_username:  sepehrkianian09
linkedin_username: sepehrkianian
# instagram_username: xplor4r
# twitter_username: xplor4r
# telegram_username: johndoe
# facebook_username: johndoe
# behance_username: johndoe
# medium_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
# formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

  # jekyll admin is causing issues with github pages, so it's disabled by default
  # - jekyll-admin 

# Jekyll Admin Config
# jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  # homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
